version: '3.8'

services:
  backend:
    build:
      context: ./error-backend
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/errorTracker
    depends_on:
      - mongo

  mongo:
    image: mongo
    container_name: mongodb
    environment:
      MONGO_INITDB_DATABASE: errorTracker
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

  frontend:
    build:
      context: ./error-buddy
    ports:
      - "3001:80"
    depends_on:
      - backend
    environment:
      - REACT_APP_BACKEND_URL=http://backend:3000

volumes:
  mongo-data: